/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jpinta;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Sergio Teacher
 */
public class Ventana3Visor extends javax.swing.JFrame {

private File Archivo;
private int salidaDelDialogo=0;
private String NombreArchivo="";
private ImageIcon miIcono;
private Image fotoTmp;
private Image fotoEscalada;

    /**
     * Creates new form Ventana3Visor
     */
    public Ventana3Visor() {
        initComponents();

        System.out.println("Iniciando Visor");
        setBounds(0,0,400,300);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraHerramientas = new javax.swing.JToolBar();
        btnAbrir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtVisor = new javax.swing.JLabel();
        txtEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana3 Visor");

        BarraHerramientas.setBackground(new java.awt.Color(0, 255, 204));
        BarraHerramientas.setRollover(true);

        btnAbrir.setBackground(new java.awt.Color(153, 204, 255));
        btnAbrir.setText("💾 Abrir");
        btnAbrir.setFocusable(false);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        BarraHerramientas.add(btnAbrir);

        btnLimpiar.setBackground(new java.awt.Color(255, 204, 153));
        btnLimpiar.setText("💣 Limpiar");
        btnLimpiar.setFocusable(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        BarraHerramientas.add(btnLimpiar);

        getContentPane().add(BarraHerramientas, java.awt.BorderLayout.PAGE_START);

        txtVisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtVisor, java.awt.BorderLayout.CENTER);

        txtEstado.setText("Img:");
        getContentPane().add(txtEstado, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed

        JFileChooser buscador = new JFileChooser();

        salidaDelDialogo = buscador.showOpenDialog(this) ;
        if( salidaDelDialogo == JFileChooser.APPROVE_OPTION ){
            Archivo = buscador.getSelectedFile();
            NombreArchivo = Archivo.getPath();

            CargaFoto(NombreArchivo);

            NombreArchivo = Archivo.getName();

            Estado("A: " + NombreArchivo);
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtVisor.setIcon(null);        
        Estado("...");
    }//GEN-LAST:event_btnLimpiarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar BarraHerramientas;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel txtEstado;
    private javax.swing.JLabel txtVisor;
    // End of variables declaration//GEN-END:variables

public void Estado(String sms){
    System.out.println("Img: " + sms);
    txtEstado.setText("Img: " + sms);
}

public void CargaFoto(String Nombre, int PORCENTAJE){
    int anchoOriginal, altoOriginal, anchoFinal, altoFinal;
    miIcono = new ImageIcon(Nombre);
    fotoTmp = miIcono.getImage();
    anchoOriginal = miIcono.getIconWidth();
    altoOriginal = miIcono.getIconHeight();
    anchoFinal = (int)( (((double) anchoOriginal) * PORCENTAJE)/100 );
    altoFinal = (int)( (((double) altoOriginal) * PORCENTAJE)/100 );

    fotoEscalada = fotoTmp.getScaledInstance(anchoFinal, altoFinal, Image.SCALE_SMOOTH);

    miIcono = new ImageIcon(fotoEscalada);
    txtVisor.setIcon(miIcono);

}
public void CargaFoto(String Nombre){
    miIcono = new ImageIcon(Nombre);
    txtVisor.setIcon(miIcono);
}

}
